import{a as v,i as m,S}from"./assets/vendor-B-D547pe.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();let f=15;async function g(o,i=1){const a="49477848-89e25f92574c797f7074d31b9",s="https://pixabay.com/api/";try{const e=await v.get(s,{params:{key:a,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:f}});return e.data.hits.length===0?(m.info({title:"No results!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),{images:[],totalHits:0}):{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Error:",e),{images:[],totalHits:0}}}let u=null;function P(o){u=new S(o,{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function p(){u&&u.refresh()}function y(o,i){const a=i.map(({webformatURL:s,largeImageURL:e,tags:r,likes:n,views:h,comments:b,downloads:L})=>`<li class="gallery-item">
            <a href="${e}" class="gallery-item-link">
            <img class="gallery-item-img" src="${s}" alt="${r}" loading="lazy" />
            </a>
            <div class="info">
            <p><b>Likes:</b>${n}</p>
            <p><b>Views:</b>${h}</p>
            <p><b>Comments:</b>${b}</p>
            <p><b>Downloads:</b>${L}</p>
            </div>
        </li>`).join("");o.insertAdjacentHTML("beforeend",a)}const t={form:document.querySelector(".form"),input:document.querySelector('[name="search-text"]'),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),addImagesBtn:document.querySelector('[type="button"]')};P(".gallery a");let c=null,l=1,d=0;t.form.addEventListener("submit",q);t.addImagesBtn.addEventListener("click",B);async function q(o){if(o.preventDefault(),l=1,d=0,t.gallery.innerHTML="",t.addImagesBtn.classList.add("visually-hidden"),c=t.input.value.trim(),c===""){m.error({title:"Error:",message:"Please fill in the search field before submitting!",position:"topRight"});return}t.loader.hidden=!1;try{const{images:i,totalHits:a}=await g(c);y(t.gallery,i),p(),d=Math.ceil(a/f),d>l&&t.addImagesBtn.classList.remove("visually-hidden")}catch(i){console.error("Error:",i)}finally{t.loader.hidden=!0,t.form.reset()}}async function B(){l+=1;try{t.addImagesBtn.classList.add("visually-hidden"),t.loader.hidden=!1;const{images:o}=await g(c,l);y(t.gallery,o),p();const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),l>=d?(t.addImagesBtn.classList.add("visually-hidden"),m.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):t.addImagesBtn.classList.remove("visually-hidden")}catch(o){console.error("Error:",o)}finally{t.loader.hidden=!0}}
//# sourceMappingURL=index.js.map
